id: PF3F00594
initial_creation_type: ocr
source_metadata:
  volumes:
    7173136573fb48479a5ba8a04aad40da:
      base_file: v057.txt
      image_group_id: I1PD95902
      title: སྐྱེ་མེད་རིན་པོ་ཆེའི་མཛོད།
      total_pages: 1605
      volume_number: 57
